import 'package:flutter/material.dart';
import 'package:homestay_host/src/themes/export_themes.dart';

ThemeData lightTheme() => ThemeData(
  useMaterial3: false,
  colorScheme: ColorScheme(
    brightness: Brightness.light,
    primary: Colors.black,
    onPrimary: Colors.white,
    primaryContainer: const Color(0xff989898),
    onPrimaryContainer: const Color(0xff050505),
    secondary: const Color(0xffFFE100),
    onSecondary: Colors.black,
    secondaryContainer: const Color(0xffFFFFB4),
    onSecondaryContainer: const Color(0xff000000),
    tertiary: const Color(0xff4885ED),
    onTertiary: Colors.white,
    tertiaryContainer: const Color(0xff4885ED),
    onTertiaryContainer: Colors.white,
    error: const Color(0xffBA1B1B),
    onError: Colors.white,
    errorContainer: const Color(0xffF9DEDC),
    onErrorContainer: const Color(0xff410E0B),
    surface: Colors.white,
    onSurface: Colors.black,
    surfaceContainerHighest: const Color(0xffE9E9E9),
    onSurfaceVariant: const Color(0xff606060),
    outline: const Color(0xff79747E),
    outlineVariant: const Color(0xffCAC4D0),
  ),
  fontFamily: 'Poppins',
  textTheme: const TextTheme(
    displayLarge: TextStyle(fontSize: 57, fontWeight: FontWeight.normal),
    displayMedium: TextStyle(fontSize: 45, fontWeight: FontWeight.normal),
    displaySmall: TextStyle(fontSize: 36, fontWeight: FontWeight.normal),
    headlineLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.normal),
    headlineMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.normal),
    headlineSmall: TextStyle(fontSize: 24, fontWeight: FontWeight.normal),
    titleLarge: TextStyle(fontSize: 22, fontWeight: FontWeight.w600),
    titleMedium: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
    titleSmall: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
    labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
    labelMedium: TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
    labelSmall: TextStyle(fontSize: 11, fontWeight: FontWeight.w600),
    bodyLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w400),
    bodyMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
    bodySmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: Colors.white,
    foregroundColor: Colors.black,
    elevation: 0,
    titleTextStyle: TextStyle(
      fontSize: 20,
      fontWeight: FontWeight.w500,
      color: Colors.black,
    ),
  ),
  elevatedButtonTheme: ElevatedButtonThemeData(
    style: ElevatedButton.styleFrom(
      disabledBackgroundColor: AppColor.containerColor.withOpacity(0.5),
      minimumSize: Size(double.infinity, 50),
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(8)
      ),
      textStyle: TextStyle(
        fontWeight: FontWeight.w600,
        fontSize: 16,
        color: Colors.white,
      ),
      backgroundColor: AppColor.containerColor,
      foregroundColor: Colors.black,
      elevation: 0,
      padding: EdgeInsets.symmetric(horizontal: 16, vertical: 14),
    ),
  ),
  inputDecorationTheme: InputDecorationTheme(
    contentPadding: EdgeInsets.symmetric(vertical: 14, horizontal: 16),
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: BorderSide(color: Colors.grey, width: 1.0),
    ),
    enabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: BorderSide(color: Colors.grey, width: 1.0),
    ),
    disabledBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: BorderSide(color: Colors.grey.shade400, width: 1.0),
    ),
    focusedBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: BorderSide(color: Colors.black, width: 1.5),
    ),
    labelStyle: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: AppColor.darkColor.withOpacity(0.6),
    ),
    hintStyle: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w500,
      color: AppColor.darkColor.withOpacity(0.6),
    ),
    floatingLabelStyle: TextStyle(
      fontSize: 14,
      fontWeight: FontWeight.w600,
      color: Colors.black,
    ),
    errorBorder: OutlineInputBorder(
      borderRadius: BorderRadius.circular(8),
      borderSide: const BorderSide(
        color: Color.fromARGB(255, 182, 41, 31),
        width: 1.5,
      ),
    ),
    errorStyle: TextStyle(
      fontSize: 14,
      color: Color.fromARGB(255, 182, 41, 31),
    ),
  ),
);

ThemeData darkTheme() => ThemeData(
  useMaterial3: false,
  colorScheme: ColorScheme(
    brightness: Brightness.dark,
    primary: Colors.white,
    onPrimary: Colors.black,
    primaryContainer: const Color(0xff989898),
    onPrimaryContainer: const Color(0xff050505),
    secondary: const Color(0xffFFE100),
    onSecondary: Colors.black,
    secondaryContainer: const Color(0xffFFFFB4),
    onSecondaryContainer: const Color(0xff000000),
    tertiary: const Color(0xff4885ED),
    onTertiary: Colors.white,
    tertiaryContainer: const Color(0xff4885ED),
    onTertiaryContainer: Colors.white,
    error: const Color(0xffBA1B1B),
    onError: Colors.white,
    errorContainer: const Color(0xffF9DEDC),
    onErrorContainer: const Color(0xff410E0B),
    surface: Colors.black,
    onSurface: Colors.white,
    surfaceContainerHighest: const Color(0xffE9E9E9),
    onSurfaceVariant: const Color(0xff606060),
    outline: const Color(0xff79747E),
    outlineVariant: const Color(0xffCAC4D0),
  ),
  fontFamily: 'Poppins',
  textTheme: const TextTheme(
    displayLarge: TextStyle(fontSize: 57, fontWeight: FontWeight.normal),
    displayMedium: TextStyle(fontSize: 45, fontWeight: FontWeight.normal),
    displaySmall: TextStyle(fontSize: 36, fontWeight: FontWeight.normal),
    headlineLarge: TextStyle(fontSize: 32, fontWeight: FontWeight.normal),
    headlineMedium: TextStyle(fontSize: 28, fontWeight: FontWeight.normal),
    headlineSmall: TextStyle(fontSize: 24, fontWeight: FontWeight.normal),
    titleLarge: TextStyle(fontSize: 22, fontWeight: FontWeight.w600),
    titleMedium: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
    titleSmall: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
    labelLarge: TextStyle(fontSize: 14, fontWeight: FontWeight.w600),
    labelMedium: TextStyle(fontSize: 12, fontWeight: FontWeight.w600),
    labelSmall: TextStyle(fontSize: 11, fontWeight: FontWeight.w600),
    bodyLarge: TextStyle(fontSize: 16, fontWeight: FontWeight.w400),
    bodyMedium: TextStyle(fontSize: 14, fontWeight: FontWeight.w400),
    bodySmall: TextStyle(fontSize: 12, fontWeight: FontWeight.w400),
  ),
);
